all_data = {
    2024: {
        "base_data": {
            "country": "Poland",
            "unit": "Lodzkie",
            "instance": 2024,
        },
        "preprocess": {
            "projects_source": "BO 2024_zadania poddane pod głosowanie",
            "votes_source": "BO 2024_głosy_bez danych os.",
            "data_dir": "2024",
            "projects_excel": "Lodzkie_2024_projects_processed",
            "votes_excel": "Lodzkie_2024_votes_processed",
        },
        "get_projects": {
            "data_dir": "2024",
            "excel_filename": "Lodzkie_2024_projects_processed",
            "columns_mapping": {
                "project_id": "project_id",
                "name": "name",
                "cost": "cost",
                "votes": "votes",
                "selected": "selected",
                "district": "district",
            },
        },
        "get_votes": {
            "excel_filename": "Lodzkie_2024_votes_processed",
            "data_dir": "2024",
            "only_valid_votes": True,
            "columns_mapping": {
                "voter_id": "voter_id",
                "sex": "sex",
                "age": "age",
                "vote_column": "vote",
                "district": "district",
            },
            "rows_iterator_handler": "one_voter_multiple_rows_no_points",
        },
        "projects_data": {
            "unit_fields": [
                "project_id",
                "cost",
                "votes",
                "name",
                "selected",
            ],
        },
        "votes_data": {
            "unit_fields": ["voter_id", "age", "sex", "vote"],
        },
        "metadata": {
            "vote_type": "choose-1",
            "rule": "greedy",
            "date_begin": "12.06.2023",
            "date_end": "30.06.2023",
            "language": "pl",
            "edition": "7",
            "currency": "PLN",
            "max_length": "1",
            "unit_description_prefix": "Voivodeship PB",
            "description_prefix": "County PB",
            "district_display_names": {
                "Belchatowski": "Bełchatowski County",
                "Brzezinski": "Brzeziński County",
                "Laski": "Łaski County",
                "Leczycki": "Łęczycki County",
                "Lodz": "Łódź (city)",
                "Lodzki_Wschodni": "Łódzki Wschodni County",
                "Lowicki": "Łowicki County",
                "Opoczynski": "Opoczyński County",
                "Pabianicki": "Pabianicki County",
                "Pajeczanski": "Pajęczański County",
                "Piotrkowski": "Piotrkowski County",
                "Poddebicki": "Poddębicki County",
                "Radomszczanski": "Radomszczański County",
                "Rawski": "Rawski County",
                "Sieradzki": "Sieradzki County",
                "Skierniewice": "Skierniewice (city)",
                "Skierniewicki": "Skierniewicki County",
                "Tomaszowski": "Tomaszowski County",
                "Wielunski": "Wieluński County",
                "Wieruszowski": "Wieruszowski County",
                "Zdunowolski": "Zduńskowolski County",
                "Zgierski": "Zgierski County",
            },
            "unit": {},
            "district": {},
        },
    },
}
