all_data = {
    2026: {
        "base_data": {
            "country": "Poland",
            "unit": "Poznań",
            "instance": 2026,
            "subdistricts": True,
        },
        "preprocess": {
            "data_dir": "2026",
            "source_votes_csv": "glosy-20251204 - UJ.csv",
            "projects_filename": "pbo26-projekty",
            "votes_filename": "pbo26-glosy",
        },
        "get_projects": {
            "data_dir": "2026",
            "excel_filename": "pbo26-projekty",
            "columns_mapping": {
                "project_id": "Numer",
                "name": "Nazwa i opis",
                "cost": "Koszt",
                "votes": "Liczba głosów",
                "district": "dzielnica",
                "subdistrict": "rodzaj",
                "selected": "czy wybrany",
            },
        },
        "get_votes": {
            "excel_filename": "pbo26-glosy",
            "excel_ext": "xlsx",
            "data_dir": "2026",
            "only_valid_votes": True,
            "columns_mapping": {
                "voter_id": "voter_id",
                "vote_column": "vote",
            },
            "rows_iterator_handler": "no_points_votes_not_separated",
            "load_subdistricts_mapping": True,
        },
        "projects_data": {
            "unit_fields": [
                "project_id",
                "cost",
                "votes",
                "name",
                "selected",
            ],
        },
        "votes_data": {
            "unit_fields": ["voter_id", "vote"],
            "districts_fields": ["voter_id", "vote"],
        },
        "metadata": {
            "vote_type": "choose-1",
            "rule": "greedy-custom",
            "date_begin": "06.10.2025",
            "date_end": "29.10.2025",
            "language": "pl",
            "min_length": "1",
            "max_length": "1",
            "edition": "14",
            "currency": "PLN",
            "unit": {},
            "district": {},
            "subdistrict_sizes": True,
            "comment": [
                "This special greedy rule works as follows: At the beginning, we sort projects based on the number of votes. Then, we fund projects that received the highest number of votes until the next project on the list does not fit within the budget. Finally, if the remaining budget is enough to fund at least 80% of that project, we fund it as well with the external reserve funds (for example, the unused funds remaining in other districts). We mark such project with number 2 in the selected column",
                "Sometimes, additional funds (for example, unused funds from other districts) are allocated to a district. These funds are used to finance the highest-voted projects that have not yet been selected. We mark such projects with number 3 in the selected column",
            ],
        },
    },
    2025: {
        "base_data": {
            "country": "Poland",
            "unit": "Poznań",
            "instance": 2025,
            "subdistricts": True,
        },
        "get_projects": {
            "data_dir": "2025",
            "excel_filename": "Wyniki PBO25 - excel",
            # "excel_ext": "xlsx",
            "columns_mapping": {
                "project_id": "Numer",
                "name": "Nazwa i opis",
                "cost": "Koszt",
                "votes": "Liczba głosów",
                "district": "dzielnica",
                "subdistrict": "rodzaj",
                "selected": "czy wybrany",
            },
        },
        "get_votes": {
            "excel_filename": "pbo25-glosy-20250102",
            "excel_ext": "xls",
            "data_dir": "2025",
            "only_valid_votes": True,
            "columns_mapping": {
                "voter_id": "voter_id",
                "vote_column": "vote",
            },
            "rows_iterator_handler": "no_points_votes_not_separated",
            "load_subdistricts_mapping": True,
        },
        "projects_data": {
            "unit_fields": [
                "project_id",
                "cost",
                "votes",
                "name",
                "selected",
            ],
        },
        "votes_data": {
            "unit_fields": ["voter_id", "vote"],
            "districts_fields": ["voter_id", "vote"],
        },
        "metadata": {
            "vote_type": "choose-1",
            "rule": "greedy-custom",
            "date_begin": "02.10.2024",
            "date_end": "23.10.2024",
            "language": "pl",
            "min_length": "1",
            "max_length": "1",
            "edition": "13",
            "currency": "PLN",
            "unit": {},
            "district": {},
            "subdistrict_sizes": True,
            "comment": [
                "This special greedy rule works as follows: At the beginning, we sort projects based on the number of votes. Then, we fund projects that received the highest number of votes until the next project on the list does not fit within the budget. Finally, if the remaining budget is enough to fund at least 80% of that project, we fund it as well with the external reserve funds (for example, the unused funds remaining in other districts). We mark such project with number 2 in the selected column",
                "Sometimes, additional funds (for example, unused funds from other districts) are allocated to a district. These funds are used to finance the highest-voted projects that have not yet been selected. We mark such projects with number 3 in the selected column",
            ],
        },
    },
    2024: {
        "base_data": {
            "country": "Poland",
            "unit": "Poznań",
            "instance": 2024,
            "subdistricts": True,
        },
        "get_projects": {
            "data_dir": "2024",
            "excel_filename": "pbo-projekty-wyniki-20240216-projekty",
            "excel_ext": "xls",
            "columns_mapping": {
                "project_id": "Numer projektu",
                "name": "Nazwa projektu",
                "cost": "Koszt",
                "votes": "Liczba głosów",
                "district": "dzielnica",
                "subdistrict": "rodzaj",
                "selected": "czy wybrany",
            },
        },
        "get_votes": {
            "excel_filename": "pbo-projekty-wyniki-20240216-glosy",
            "excel_ext": "xls",
            "data_dir": "2024",
            "only_valid_votes": True,
            "columns_mapping": {
                "voter_id": "voter_id",
                "vote_column": "vote",
            },
            "rows_iterator_handler": "no_points_votes_not_separated",
            "load_subdistricts_mapping": True,
        },
        "projects_data": {
            "unit_fields": [
                "project_id",
                "cost",
                "votes",
                "name",
                "selected",
            ],
        },
        "votes_data": {
            "unit_fields": ["voter_id", "vote"],
            "districts_fields": ["voter_id", "vote"],
        },
        "metadata": {
            "vote_type": "choose-1",
            "rule": "greedy-custom",
            "date_begin": "13.09.2023",
            "date_end": "27.09.2023",
            "language": "pl",
            "min_length": "1",
            "max_length": "1",
            "edition": "12",
            "currency": "PLN",
            "unit": {},
            "district": {},
            "subdistrict_sizes": True,
            "comment": [
                "This special greedy rule works as follows: At the beginning, we sort projects based on the number of votes. Then, we fund projects that received the highest number of votes until the next project on the list does not fit within the budget. Finally, if the remaining budget is enough to fund at least 80% of that project, we fund it as well with the external reserve funds (for example, the unused funds remaining in other districts). We mark such project with number 2 in the selected column",
                "Sometimes, additional funds (for example, unused funds from other districts) are allocated to a district. These funds are used to finance the highest-voted projects that have not yet been selected. We mark such projects with number 3 in the selected column",
            ],
        },
    },
}
